spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 64MB
      max-file-size: 256MB
      max-request-size: 256MB

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2996362441
    url: jdbc:postgresql://localhost:5432/spring_cs307

server:
  port: 8181

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:edu/sustech/cs307/mapper/xml/*.xml
  type-aliases-package: edu.sustech.cs307.entity